# Generated by Django 3.0.6 on 2020-06-03 17:26

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP_name', models.CharField(max_length=10)),
                ('LP_img', imagekit.models.fields.ProcessedImageField(upload_to='media')),
            ],
        ),
    ]
