# Generated by Django 3.0.6 on 2020-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp',
            name='LP_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
