# Generated by Django 3.0.6 on 2020-06-04 04:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200604_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP_name', models.CharField(max_length=10)),
                ('LP_img', imagekit.models.fields.ProcessedImageField(upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='LP',
        ),
    ]
