# Generated by Django 3.0.6 on 2020-06-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20200604_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POST',
            new_name='LP',
        ),
    ]
