# Generated by Django 3.0.6 on 2020-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20200604_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP_name', models.CharField(max_length=100)),
                ('LP_img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='lpForm',
        ),
    ]
